# curl -X POST localhost:8080/collect -H "Content-type: application/json" -d '{"from":["33660481","33663703","33666179"],"to":"33667779", "ships":{"large_cargo_ship":120}}'
POST localhost:8080/collect
Content-Type: application/json

{
  "from": [
    "33624132",
    "33625085",
    "33626410",
    "33631643"
  ],
  "to": "33620962",
  "ships": {
    "large_cargo_ship": 300
  },
  "missionType": "Transport"
}

###

