# spread
POST localhost:8080/spread
Content-Type: application/json

{
  "from" : "33620962",
  "to" : [
    "33632829"
  ],
  "ships" : {
    "large_cargo_ship" : 500
  },
  "resources" : {
    "metal" : 12700000,
    "crystal" : 4100000,
    "deuterium" : 0,
    "energy" : 0
  },
  "missionType" : "Transport"
}

###

